home:             "/"
articles:         "/articles/"
repository:       "https://github.com/deliveroo/deliveroo.engineering"
developer_portal: "https://developers.deliveroo.com/"
design_blog:      "https://deliveroo.design/"
navigation:
  - url:   '/articles/'
    title: 'Articles'
  - url:   '/authors/'
    title: 'Authors'
